[build]
  command = "npm install && npm run build"
  functions = "functions"
[[redirects]]
  from = '/'
  to = '/.netlify/functions/server/'
  force = true
  status = 200
[[redirects]]
  from = '/index.html'
  to = '/.netlify/functions/server/'
  force = true
  status = 200
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
